"""Add calendar fields to Task model

Revision ID: 063bbcbbd41c
Revises: f92bb967f24d
Create Date: 2024-11-19 21:26:03.288858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063bbcbbd41c'
down_revision = 'f92bb967f24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
