"""empty message

Revision ID: a41b3040345c
Revises: ed622ba48f4f
Create Date: 2024-10-28 16:27:26.345675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41b3040345c'
down_revision = 'ed622ba48f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
