"""Add quadrant field to Task model

Revision ID: d52da5f9360f
Revises: a41b3040345c
Create Date: 2024-11-08 14:16:26.493163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52da5f9360f'
down_revision = 'a41b3040345c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quadrant', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('quadrant')

    # ### end Alembic commands ###
