"""Add calendar fields to task model

Revision ID: f1a6cccfb34e
Revises: 063bbcbbd41c
Create Date: 2024-11-19 21:44:06.863952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a6cccfb34e'
down_revision = '063bbcbbd41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_hour', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('assigned_hour')
        batch_op.drop_column('assigned_day')

    # ### end Alembic commands ###
